# Generated by Django 3.1 on 2020-11-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlogdata', '0004_auto_20201124_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandates',
            name='CTC',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
