# Generated by Django 3.1 on 2020-11-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlogdata', '0005_auto_20201124_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandates',
            name='NoticePeriod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
